version: '3'

services:
  db:
    image: postgres 
    networks:
      - todo_net
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - todo_net
    depends_on:
      - db

networks:
  todo_net: